app/views/home.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import current_user

# from ..models.models import Usuario

home = Blueprint("home", __name__)

@home.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for('auth.verificar_roles'))
    return render_template("home.html")

@home.route("/testeo4")
def testeo4():
    return render_template("user/seleccionarperfil.html")

app/templates/base/alerts.html
<div>
  {% with messages = get_flashed_messages(with_categories=True) %}
   {% if messages %}
    {% for category, message in messages %}
     {% if category == "error" %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </button>
        </div>
        {% elif category == 'success' %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </button>
        </div>
        {% else %}
        <div class="alert alert-warning alter-dismissible fade show" role="alert">
          {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </button>
        </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>

app/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block titulo %}{% endblock %}</title>

    {% block head %}
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <!-- Google Fonts - Roboto -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300&display=swap" rel="stylesheet">
    
    <!-- CSS -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/base.css')}}"
    />
    {% endblock %}
  </head>
  
  <body>
    <!-- Block navbar -->
    {% block navbar %}
    {% include 'base/nav.html' %}
    {% endblock %}


    <!-- Block sidebar -->
    {% block sidebar %}
    {% include 'base/sidebar.html' %}
    {% endblock %}
        
    
    <!-- Block Content -->
    {% block content %}
    {% endblock %}


    <!-- Block de las alertas -->
    {% block alertas %}
    {% include 'base/alerts.html' %}
    {% endblock %}


    {% block script%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
    {% endblock %}
  </body>
  
</html>

app/templates/base/nav.html
<nav
  id="main-navbar"
  class="navbar navbar-expand-md navbar-light bg-white fixed-top"
>
  <!-- Container wrapper -->
  <div class="container-fluid">
    
    {% if current_user.is_authenticated%}
    <!-- Toggle button sidebar -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu"
      aria-expanded="false"
      aria-controls="sidebarMenu"
    >
      <i class="bi bi-list-task"></i>
    </button>
    {%endif%}
    <!-- Brand -->
    <a
      class="navbar-brand mx-2"
      href="{{url_for('home.index')}}"
      rel="home"
    >
      <strong>I.S.P.P. N° 1</strong> 
    </a>

    <!-- Toggle button navbar -->
    <button
      class="navbar-toggler collapsed"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbartopside"
      aria-controls="navbartopside"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
    <i class="bi bi-caret-down-fill"></i>
    </button>

    <!-- Right links -->
    <div class="navbar-collapse collapse" id="navbartopside">
      <ul class="navbar-nav ms-auto d-flex flex-md-row flex-column align-items-center">
        <!-- Notification dropdown -->
        {% if current_user.is_authenticated %}
        {%if session['perfilid']%}
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="{{url_for('usuario.index')}}">
            <i class="bi bi-house-door-fill mx-1"></i>Inicio
          </a>
        </li>
        {%endif%}
        <li class="nav-item me-3 me-lg-0"> 
          <a class="nav-link" href="{{url_for('auth.logout')}}">
            <i class="bi bi-box-arrow-in-right mx-1"></i>Cerrar Sesión
          </a>
        </li>
        {% else %}
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="{{url_for('home.index')}}">
            <i class="bi bi-house-door-fill mx-1"></i>Inicio
          </a>
        </li>
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="{{url_for('auth.login')}}">
            <i class="bi bi-person-circle mx-1"></i>Iniciar Sesion
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <!-- Container wrapper -->
</nav>

app/templates/base/sidebar.html
{%if current_user.is_authenticated and session['perfilid'] %}
<nav id="sidebarMenu" class="collapse d-md-block sidebar col-2 collapse bg-white">
  <div class="position-sticky h-100">
    <div class="list-group list-group-flush h-100 d-flex flex-column bd-highlight mb-3">
      <a href="{{url_for('usuario.mostrar_Datospersonales_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong>Datos Personales</strong> </span>
      </a>
      <!-- Bedeles -->
      {%if session['perfilid'] == 5%}
      <!-- <a href="{{url_for('bedel.mostrar_datoslaborales_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span><strong> Datos Laborales </strong></span>
      </a> -->
      <a href="{{url_for('bedel.mostrar_carreras_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Mis carreras </strong> </span>
      </a>
      <!-- <a href="{{url_for('bedel.alta_añadirusuario_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Añadir usuario </strong> </span>
      </a> -->
      <!-- Si el usuarioperfil del perfil que se logio está habilitado -->
      {% if session['usuarioperfilactivo']%}
      <a href="{{url_for('bedel.mostrar_alumnos')}}" class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Administrar Usuarios</strong> </span>
      </a>
      {%endif%}

      {%endif%}

      <!-- Docentes -->
      {%if session['perfilid'] == 6%}
      <a href="#" class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Mis Carreras </strong></span>
      </a>
      {%endif%}

      <!-- Alumno -->
      {%if session['perfilid'] == 7%}
      <a href="{{url_for('alumno.mostrar_datossecundaria_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Datos Secundaria</strong> </span>
      </a>
      <!-- <a href="{{url_for('alumno.mostrar_datosacademicos_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Datos Academicos </strong> </span>
      </a> -->
      <a href="{{url_for('alumno.mostrar_carreras_usuarioperfil')}}"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong> Mis carreras </strong> </span>
      </a>
      <!-- inscripcion a materias -->
      <!-- <a href="#"
        class="list-group-item list-group-item-action py-2 ripple">
        <span> <strong>Inscripcion a materia</strong> </span>
      </a> -->
      {%endif%}


      <div class="cambiarperfil mt-auto bd-highlight" id="cambiarperfil">
        <a href="{{url_for('auth.seleccionar_perfil')}}" class="list-group-item list-group-item-action py-2 ripple ">
          <span> <strong> Cambiar Perfil - <div id="perfilidobtenido" style="display:inline;"></div> </strong> </span>
        </a>
      </div>


    </div>
  </div>
</nav>
{%endif%}